from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, Optional


_DASHBOARD_SNAPSHOT: Dict[str, Any] = {
    "meta": {
        "application": "attas Personal Agent",
        "mode": "Prototype Web Terminal",
        "plaza_url": "http://127.0.0.1:8011",
        "connection": "Simulation Ready",
        "last_sync": "2026-03-28 08:45 CST",
        "storage_pool": "Filesystem + SQLite edge cache",
        "profile": "Personal research desk",
    },
    "hero": {
        "eyebrow": "Multi-asset operator surface",
        "headline": "A personal terminal for pulses, positions, providers, and workflow cost.",
        "summary": (
            "Track market structure, compare pulser quality, monitor analytics, and stage transactions "
            "through the attas network from one browser-based command layer."
        ),
        "stats": [
            {"label": "Open windows", "value": "06"},
            {"label": "Live pulse feeds", "value": "128"},
            {"label": "Queued analytics", "value": "04"},
            {"label": "Provider spend", "value": "$486/mo"},
        ],
    },
    "coverage": [
        {"label": "Facts", "value": "84", "detail": "portable pulse definitions"},
        {"label": "Analytics", "value": "29", "detail": "derived signals and models"},
        {"label": "Artifacts", "value": "15", "detail": "reports, notes, and casts"},
        {"label": "Connected agents", "value": "11", "detail": "pulsers, phemars, castrs"},
    ],
    "watchlist": [
        {
            "symbol": "NVDA",
            "name": "NVIDIA",
            "asset_class": "Stock",
            "price": 1021.44,
            "change_pct": 1.82,
            "pulse_count": 18,
            "provider": "YFinancePulser",
            "note": "Revision breadth still rising with AI infra demand.",
            "spark": [94, 98, 101, 104, 102, 108, 112],
        },
        {
            "symbol": "MSFT",
            "name": "Microsoft",
            "asset_class": "Stock",
            "price": 468.12,
            "change_pct": 0.74,
            "pulse_count": 14,
            "provider": "FinnhubPulser",
            "note": "Azure mix remains the key margin unlock.",
            "spark": [79, 80, 81, 83, 82, 84, 85],
        },
        {
            "symbol": "EURUSD",
            "name": "Euro / US Dollar",
            "asset_class": "FX",
            "price": 1.0934,
            "change_pct": -0.21,
            "pulse_count": 9,
            "provider": "MarketstackPulser",
            "note": "Carry stable, but growth differential has narrowed.",
            "spark": [62, 61, 62, 60, 59, 58, 57],
        },
        {
            "symbol": "BTC-USD",
            "name": "Bitcoin",
            "asset_class": "Crypto",
            "price": 71842.15,
            "change_pct": 2.94,
            "pulse_count": 12,
            "provider": "OpenAIPulser",
            "note": "Spot demand returned after a two-session pause.",
            "spark": [51, 54, 58, 57, 63, 68, 72],
        },
        {
            "symbol": "CL",
            "name": "WTI Crude",
            "asset_class": "Commodity",
            "price": 82.61,
            "change_pct": 0.37,
            "pulse_count": 8,
            "provider": "AlphaVantagePulser",
            "note": "Supply risk premium persists but curve is orderly.",
            "spark": [70, 72, 73, 71, 74, 75, 76],
        },
    ],
    "providers": [
        {
            "name": "YFinancePulser",
            "category": "Market data",
            "coverage": "Equities, ETFs, FX",
            "latency_ms": 310,
            "monthly_cost": 0,
            "quality": "Starter",
            "reliability": "4/5",
        },
        {
            "name": "FinnhubPulser",
            "category": "Fundamentals + quotes",
            "coverage": "Equities, news, filings",
            "latency_ms": 180,
            "monthly_cost": 149,
            "quality": "Research",
            "reliability": "5/5",
        },
        {
            "name": "AlphaVantagePulser",
            "category": "Indicators",
            "coverage": "Indicators, FX, crypto",
            "latency_ms": 420,
            "monthly_cost": 79,
            "quality": "Analyst bench",
            "reliability": "3/5",
        },
        {
            "name": "OpenAIPulser",
            "category": "Reasoning + synthesis",
            "coverage": "Artifacts and commentary",
            "latency_ms": 960,
            "monthly_cost": 258,
            "quality": "Premium",
            "reliability": "4/5",
        },
    ],
    "positions": [
        {
            "symbol": "NVDA",
            "quantity": 120,
            "avg_cost": 884.10,
            "last_price": 1021.44,
            "pnl": 16480.80,
            "allocation": 18.2,
            "thesis": "AI capex cycle remains under-owned by allocators.",
        },
        {
            "symbol": "MSFT",
            "quantity": 95,
            "avg_cost": 402.35,
            "last_price": 468.12,
            "pnl": 6248.15,
            "allocation": 14.7,
            "thesis": "Cloud durability plus balance-sheet quality.",
        },
        {
            "symbol": "TLT",
            "quantity": 260,
            "avg_cost": 92.14,
            "last_price": 95.08,
            "pnl": 764.40,
            "allocation": 8.1,
            "thesis": "Adds duration into slower nominal growth scenarios.",
        },
        {
            "symbol": "BTC-USD",
            "quantity": 1.8,
            "avg_cost": 64110.00,
            "last_price": 71842.15,
            "pnl": 13917.87,
            "allocation": 6.4,
            "thesis": "Asymmetric liquidity beta with disciplined size.",
        },
    ],
    "analytics": [
        {
            "title": "Semiconductor momentum lattice",
            "owner": "ta.pulser",
            "schedule": "Every 30 min",
            "runtime": "42 sec",
            "status": "Running",
            "impact": "Raised conviction on 4 names",
        },
        {
            "title": "Macro risk radar",
            "owner": "Macro Phemar",
            "schedule": "Daily 06:00",
            "runtime": "4 min",
            "status": "Complete",
            "impact": "Growth pulse softened in Europe",
        },
        {
            "title": "Crypto overnight monitor",
            "owner": "OpenAIPulser",
            "schedule": "Hourly",
            "runtime": "58 sec",
            "status": "Queued",
            "impact": "Waiting for funding-rate snapshot",
        },
        {
            "title": "Treasury ladder planner",
            "owner": "PathPulser",
            "schedule": "On demand",
            "runtime": "18 sec",
            "status": "Ready",
            "impact": "Cash sweep rebalance available",
        },
    ],
    "transactions": [
        {
            "time": "08:42",
            "side": "BUY",
            "symbol": "TLT",
            "quantity": 40,
            "venue": "IBKR",
            "status": "Queued",
        },
        {
            "time": "08:28",
            "side": "SELL",
            "symbol": "QQQ",
            "quantity": 12,
            "venue": "Manual import",
            "status": "Booked",
        },
        {
            "time": "08:10",
            "side": "BUY",
            "symbol": "BTC-USD",
            "quantity": 0.15,
            "venue": "Coinbase",
            "status": "Confirmed",
        },
    ],
    "workspaces": [
        {
            "id": "semis",
            "name": "Semiconductor Conviction Deck",
            "kind": "Symbol Grid",
            "focus": "NVDA / AMD / TSM",
            "status": "Pinned",
            "owner": "attas-user",
            "description": "Cross-check price action, estimate revisions, and research artifacts across multiple pulsers.",
            "panes": ["Pulse tape", "Cost map", "AI notes", "Trade blotter"],
            "highlights": [
                "NVDA pulse and provider agreement tightened to 4 bps.",
                "Two analyst artifacts moved from watch to positive.",
            ],
        },
        {
            "id": "macro",
            "name": "Macro Risk Radar",
            "kind": "Event Window",
            "focus": "Rates / FX / Liquidity",
            "status": "Live",
            "owner": "attas-user",
            "description": "A rolling view of treasury, FX, and liquidity pulses with event-driven commentary.",
            "panes": ["Curve monitor", "FX basket", "Calendar", "Phema brief"],
            "highlights": [
                "EUR pulse breadth softened as growth proxies drifted lower.",
                "US 10Y risk window widened around payroll revisions.",
            ],
        },
        {
            "id": "crypto",
            "name": "Crypto Overnight",
            "kind": "Signal Stack",
            "focus": "BTC / ETH / Funding",
            "status": "Review",
            "owner": "attas-user",
            "description": "Funding, flows, and cross-venue momentum in a compact overnight command surface.",
            "panes": ["Spot tape", "Funding", "Exchange health", "Alert queue"],
            "highlights": [
                "Funding normalized while spot volumes re-accelerated.",
                "Open interest recovered without disorderly liquidation behavior.",
            ],
        },
    ],
    "activity": [
        {
            "time": "08:47",
            "headline": "Pulse refreshed for NVDA last trade",
            "detail": "YFinancePulser and FinnhubPulser agreed within 4 bps on the current tape.",
        },
        {
            "time": "08:36",
            "headline": "New artifact cast for Macro Risk Radar",
            "detail": "PptCastr generated a four-slide morning brief for treasury review.",
        },
        {
            "time": "08:19",
            "headline": "Broker import reconciled",
            "detail": "Three overnight fills matched local transaction records without manual intervention.",
        },
        {
            "time": "07:58",
            "headline": "Provider cost comparison updated",
            "detail": "AlphaVantagePulser moved above budget threshold for high-frequency usage.",
        },
    ],
    "browser": {
        "title": "Research Browser",
        "workspace_label": "WS",
        "layout_name": "Cross-Asset Sample Layout",
        "query": "AUD/EUR spot monitor",
        "default_view": "fx",
        "menus": [
            "Markets",
            "Macro",
            "Company",
            "News",
            "Charting",
            "Monitoring",
            "Analytics & Calculators",
            "Search Tools",
            "Sustainability",
        ],
        "bookmarks": [
            {
                "id": "fx-board",
                "label": "FX Spot Monitor",
                "url": "attas://workspace/fx/spot-monitor",
                "category": "fx",
                "view_id": "fx",
                "symbol_id": "aud-eur",
                "summary": "Asia-Pacific FX board with forwards, flow headlines, and time & sales for active crosses.",
            },
            {
                "id": "equity-board",
                "label": "Equity Monitor",
                "url": "attas://workspace/equities/semiconductor-deck",
                "category": "equity",
                "view_id": "equities",
                "symbol_id": "nvda",
                "summary": "Company monitor for semiconductors and megacap platforms with valuation and tape sidecars.",
            },
            {
                "id": "crypto-board",
                "label": "Crypto Overnight",
                "url": "attas://workspace/crypto/overnight",
                "category": "crypto",
                "view_id": "crypto",
                "symbol_id": "btc-usd",
                "summary": "Exchange monitor with funding, order flow, and derivative tape for overnight crypto risk.",
            },
            {
                "id": "commodities-board",
                "label": "Commodities Curve",
                "url": "attas://workspace/commodities/curve",
                "category": "commodity",
                "view_id": "commodities",
                "symbol_id": "cl",
                "summary": "Curve monitor for oil, metals, and gas with inventory context and front-month trade prints.",
            },
            {
                "id": "pulse-catalog",
                "label": "Pulse Catalog",
                "url": "attas://catalog/finance-core",
                "category": "data",
                "view_id": "equities",
                "symbol_id": "msft",
                "summary": "Core pulse definitions, mappings, and profiles used across market and research windows.",
            },
            {
                "id": "trade-blotter",
                "label": "Trade Blotter",
                "url": "attas://transactions/blotter",
                "category": "routing",
                "view_id": "fx",
                "symbol_id": "eur-usd",
                "summary": "Recent orders, imported fills, broker handoff state, and routing audit details.",
            },
        ],
        "views": [
            {
                "id": "fx",
                "label": "FX",
                "subtitle": "Spot, forwards, flow headlines, and time & sales",
                "market_label": "APAC",
                "workspace_tag": "Monitor MON",
                "symbol_prompt": "Search pair, topic, or saved board...",
                "monitor_title": "FX Spot Monitor",
                "monitor_columns": [
                    {"id": "pair", "label": "Pair"},
                    {"id": "bias", "label": "Bias"},
                    {"id": "bid_offer", "label": "Bid/Offer"},
                    {"id": "change", "label": "%"},
                    {"id": "range", "label": "Trading Range"},
                ],
                "monitor_rows": [
                    {"pair": "USD/JPY", "bias": "▲", "bid_offer": "160.31 / 34", "change": "+0.18", "range": "159.94 - 160.52"},
                    {"pair": "AUD/USD", "bias": "▼", "bid_offer": "0.6675 / 77", "change": "-0.31", "range": "0.6658 - 0.6704"},
                    {"pair": "NZD/USD", "bias": "▼", "bid_offer": "0.6044 / 46", "change": "-0.22", "range": "0.6038 - 0.6072"},
                    {"pair": "USD/CNH", "bias": "▲", "bid_offer": "7.261 / 12", "change": "+0.09", "range": "7.248 - 7.269"},
                    {"pair": "EUR/USD", "bias": "▼", "bid_offer": "1.1508 / 12", "change": "-0.08", "range": "1.1499 - 1.1534"},
                ],
                "feed": [
                    {"time": "08:42:21", "source": "ADNEWS", "headline": "Rio Tinto acquisition bolsters Australian dollar trade-sensitive complex."},
                    {"time": "08:31:11", "source": "DAX40", "headline": "Cyclical weakness in Europe keeps pressure on AUD/EUR crosses."},
                    {"time": "08:29:09", "source": "GLODP", "headline": "Australian dollars fall for a second straight session as rates stabilize."},
                    {"time": "08:24:50", "source": "Macro", "headline": "Debt market pressure eases, but growth differential still favors the euro."},
                ],
                "symbols": [
                    {
                        "id": "aud-eur",
                        "ticker": "AUD/EUR",
                        "name": "Australian Dollar / Euro",
                        "display_price": "0.5982",
                        "change_pct": -0.41,
                        "bid": "0.5981",
                        "ask": "0.5983",
                        "note": "Falls for a second consecutive session as European cyclical data stabilizes.",
                        "story_title": "AUD/EUR slips as euro resilience outweighs APAC risk appetite.",
                        "story_summary": "The cross is softer on modest euro support and a calmer European rates backdrop, even with broader risk appetite holding up through Asia.",
                        "story_points": [
                            "Forward points are still pricing a gentle carry headwind into month-end.",
                            "Provider agreement is tight enough to route low-latency monitoring through starter feeds.",
                            "Macro Phemar still flags the pair as sensitive to payroll revisions and ECB repricing.",
                        ],
                        "tool_title": "FX Forwards Calculator",
                        "tool_metrics": [
                            {"label": "Trade Date", "value": "28 Mar 2026"},
                            {"label": "Value Date", "value": "31 Mar 2026"},
                            {"label": "Spot", "value": "0.5982"},
                            {"label": "Curve Basis", "value": "-0.4 bp"},
                        ],
                        "tool_rows": [
                            {"tenor": "ON", "value_date": "31 Mar 2026", "swap_points": "0.41 / 0.45", "outright": "0.59861"},
                            {"tenor": "TN", "value_date": "01 Apr 2026", "swap_points": "0.59 / 0.64", "outright": "0.59878"},
                            {"tenor": "1W", "value_date": "07 Apr 2026", "swap_points": "2.81 / 2.96", "outright": "0.60108"},
                        ],
                        "tape_title": "AUD/EUR Spot Time & Sales",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Mid"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:45:09.902", "bid": "0.5981", "ask": "0.5983", "mid": "0.5982", "venue": "ABSG"},
                            {"time": "08:45:04.971", "bid": "0.5980", "ask": "0.5982", "mid": "0.5981", "venue": "RFXM"},
                            {"time": "08:45:01.286", "bid": "0.5981", "ask": "0.5983", "mid": "0.5982", "venue": "TKZB"},
                        ],
                    },
                    {
                        "id": "eur-usd",
                        "ticker": "EUR/USD",
                        "name": "Euro / US Dollar",
                        "display_price": "1.1508",
                        "change_pct": -0.08,
                        "bid": "1.1508",
                        "ask": "1.1512",
                        "note": "Consolidating near the middle of the weekly range after a softer U.S. session.",
                        "story_title": "EUR/USD range tightens as both central bank paths stay largely priced.",
                        "story_summary": "Short-term price action is orderly, with investors waiting for the next labor-market catalyst and ECB commentary on inflation persistence.",
                        "story_points": [
                            "Liquidity is deepest through the London handoff.",
                            "Cross-provider last-trade variance remains under 1 bp.",
                            "Rates path commentary is still the main event driver.",
                        ],
                        "tool_title": "FX Cross Monitor",
                        "tool_metrics": [
                            {"label": "Session", "value": "Europe / U.S."},
                            {"label": "Spot", "value": "1.1508"},
                            {"label": "Daily Range", "value": "1.1499 - 1.1534"},
                            {"label": "Vol Surface", "value": "Muted"},
                        ],
                        "tool_rows": [
                            {"tenor": "1W", "value_date": "04 Apr 2026", "swap_points": "2.1 / 2.3", "outright": "1.15103"},
                            {"tenor": "1M", "value_date": "30 Apr 2026", "swap_points": "8.7 / 9.1", "outright": "1.15170"},
                            {"tenor": "3M", "value_date": "30 Jun 2026", "swap_points": "27.2 / 28.0", "outright": "1.15356"},
                        ],
                        "tape_title": "EUR/USD Spot Time & Sales",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Mid"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:51.602", "bid": "1.1508", "ask": "1.1512", "mid": "1.1510", "venue": "ABSG"},
                            {"time": "08:44:47.971", "bid": "1.1508", "ask": "1.1511", "mid": "1.15095", "venue": "RFXM"},
                            {"time": "08:44:42.264", "bid": "1.1509", "ask": "1.1513", "mid": "1.1511", "venue": "TKZB"},
                        ],
                    },
                    {
                        "id": "usd-jpy",
                        "ticker": "USD/JPY",
                        "name": "US Dollar / Japanese Yen",
                        "display_price": "160.34",
                        "change_pct": 0.18,
                        "bid": "160.31",
                        "ask": "160.34",
                        "note": "Still pressing the upper edge of the intervention sensitivity zone.",
                        "story_title": "USD/JPY edges higher as U.S. yields stay elevated into the Asia close.",
                        "story_summary": "Rate support remains constructive for the pair, though traders continue to keep one eye on official rhetoric and volatility spikes.",
                        "story_points": [
                            "Intervention risk is the main reason liquidity thins near local highs.",
                            "Macro pulse still tags yen weakness as carry-driven rather than panic-driven.",
                            "Short-dated vols remain sticky despite calmer spot action.",
                        ],
                        "tool_title": "Intervention Risk Ladder",
                        "tool_metrics": [
                            {"label": "Spot", "value": "160.34"},
                            {"label": "Risk Band", "value": "High"},
                            {"label": "1W Vol", "value": "10.8%"},
                            {"label": "Carry Bias", "value": "Positive USD"},
                        ],
                        "tool_rows": [
                            {"tenor": "Spot", "value_date": "28 Mar 2026", "swap_points": "--", "outright": "160.34"},
                            {"tenor": "1W", "value_date": "04 Apr 2026", "swap_points": "18 / 21", "outright": "160.53"},
                            {"tenor": "1M", "value_date": "30 Apr 2026", "swap_points": "76 / 83", "outright": "161.12"},
                        ],
                        "tape_title": "USD/JPY Spot Prints",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Mid"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:11.019", "bid": "160.31", "ask": "160.34", "mid": "160.33", "venue": "ABSG"},
                            {"time": "08:43:58.667", "bid": "160.30", "ask": "160.33", "mid": "160.32", "venue": "EBS"},
                            {"time": "08:43:42.115", "bid": "160.29", "ask": "160.32", "mid": "160.31", "venue": "RFXM"},
                        ],
                    },
                ],
            },
            {
                "id": "equities",
                "label": "Equities",
                "subtitle": "Company monitor, news flow, valuation, and trade log",
                "market_label": "US Tech",
                "workspace_tag": "Semis",
                "symbol_prompt": "Search ticker, company, portfolio, or pulse...",
                "monitor_title": "Equity Monitor",
                "monitor_columns": [
                    {"id": "symbol", "label": "Symbol"},
                    {"id": "bias", "label": "Bias"},
                    {"id": "last", "label": "Last"},
                    {"id": "change", "label": "%"},
                    {"id": "focus", "label": "Focus"},
                ],
                "monitor_rows": [
                    {"symbol": "NVDA", "bias": "▲", "last": "1021.44", "change": "+1.82", "focus": "AI infra"},
                    {"symbol": "AMD", "bias": "▲", "last": "198.62", "change": "+1.09", "focus": "Server mix"},
                    {"symbol": "TSM", "bias": "▲", "last": "176.15", "change": "+0.64", "focus": "Foundry capex"},
                    {"symbol": "MSFT", "bias": "▲", "last": "468.12", "change": "+0.74", "focus": "Azure demand"},
                    {"symbol": "AMZN", "bias": "▼", "last": "195.33", "change": "-0.28", "focus": "Cloud margins"},
                ],
                "feed": [
                    {"time": "08:39:14", "source": "Company", "headline": "NVIDIA supply chain checks point to another quarter of accelerator demand strength."},
                    {"time": "08:34:29", "source": "Street", "headline": "TSM capacity commentary eases near-term concerns around AI packaging constraints."},
                    {"time": "08:28:11", "source": "Pulse", "headline": "Revision breadth remains strongest in semiconductors and infrastructure software."},
                    {"time": "08:20:46", "source": "Macro", "headline": "Lower growth anxiety supports long-duration software alongside cyclically exposed semis."},
                ],
                "symbols": [
                    {
                        "id": "nvda",
                        "ticker": "NVDA",
                        "name": "NVIDIA",
                        "display_price": "$1021.44",
                        "change_pct": 1.82,
                        "bid": "$1021.10",
                        "ask": "$1021.58",
                        "note": "Capex winners continue to dominate revision leadership.",
                        "story_title": "NVIDIA remains the center of the AI infrastructure trade.",
                        "story_summary": "Pulse agreement across pricing, news, and analyst artifacts still favors upside participation while valuation remains the main debate.",
                        "story_points": [
                            "Latest pulse spread versus peer group still signals premium growth durability.",
                            "Order momentum remains stronger than broader semiconductor breadth.",
                            "Trade blotter suggests users are adding on consolidation rather than chasing the tape.",
                        ],
                        "tool_title": "Valuation Lattice",
                        "tool_metrics": [
                            {"label": "FY1 Rev Growth", "value": "63%"},
                            {"label": "NTM EV/Sales", "value": "21.4x"},
                            {"label": "Gross Margin", "value": "76.2%"},
                            {"label": "Crowding", "value": "High"},
                        ],
                        "tool_rows": [
                            {"tenor": "Bull", "value_date": "Target", "swap_points": "1240", "outright": "AI demand + margin"},
                            {"tenor": "Base", "value_date": "Target", "swap_points": "1085", "outright": "Sustained capex"},
                            {"tenor": "Bear", "value_date": "Target", "swap_points": "845", "outright": "Normalization risk"},
                        ],
                        "tape_title": "NVDA Trade Log",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Last"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:59.774", "bid": "1021.10", "ask": "1021.58", "mid": "1021.44", "venue": "NASDAQ"},
                            {"time": "08:44:52.101", "bid": "1020.80", "ask": "1021.30", "mid": "1021.12", "venue": "ARCA"},
                            {"time": "08:44:41.008", "bid": "1020.44", "ask": "1020.92", "mid": "1020.68", "venue": "BATS"},
                        ],
                    },
                    {
                        "id": "msft",
                        "ticker": "MSFT",
                        "name": "Microsoft",
                        "display_price": "$468.12",
                        "change_pct": 0.74,
                        "bid": "$467.90",
                        "ask": "$468.20",
                        "note": "Azure quality plus balance sheet makes it the defensive AI compounder.",
                        "story_title": "Microsoft is still the cleaner duration-quality expression inside AI.",
                        "story_summary": "The mix of cloud durability and disciplined capital returns keeps the name high on quality screens, even when semis dominate momentum.",
                        "story_points": [
                            "Azure demand remains the main driver of positive revisions.",
                            "Valuation has room when rates stabilize and quality gets bid.",
                            "Provider commentary is unusually consistent across research feeds.",
                        ],
                        "tool_title": "Cloud Quality Deck",
                        "tool_metrics": [
                            {"label": "Azure Mix", "value": "Rising"},
                            {"label": "NTM FCF Yield", "value": "2.9%"},
                            {"label": "Net Cash", "value": "Strong"},
                            {"label": "Quality Rank", "value": "Top decile"},
                        ],
                        "tool_rows": [
                            {"tenor": "Bull", "value_date": "Target", "swap_points": "510", "outright": "Cloud + AI pull-through"},
                            {"tenor": "Base", "value_date": "Target", "swap_points": "485", "outright": "Steady enterprise spend"},
                            {"tenor": "Bear", "value_date": "Target", "swap_points": "428", "outright": "Margin pressure"},
                        ],
                        "tape_title": "MSFT Trade Log",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Last"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:11.301", "bid": "467.90", "ask": "468.20", "mid": "468.12", "venue": "NASDAQ"},
                            {"time": "08:43:56.889", "bid": "467.72", "ask": "468.05", "mid": "467.98", "venue": "ARCA"},
                            {"time": "08:43:35.644", "bid": "467.40", "ask": "467.84", "mid": "467.63", "venue": "EDGX"},
                        ],
                    },
                    {
                        "id": "tsm",
                        "ticker": "TSM",
                        "name": "TSMC",
                        "display_price": "$176.15",
                        "change_pct": 0.64,
                        "bid": "$176.02",
                        "ask": "$176.19",
                        "note": "Foundry capex and packaging supply remain key bottlenecks to watch.",
                        "story_title": "TSMC is the supply-side governor on the AI buildout.",
                        "story_summary": "Capacity commentary remains supportive, and cross-provider monitoring points to fewer near-term bottleneck fears than earlier in the quarter.",
                        "story_points": [
                            "Packaging pulse improved across both research and supplier notes.",
                            "Foundry utilization keeps tightening high-end node capacity.",
                            "Margin outlook still depends on mix discipline and FX swings.",
                        ],
                        "tool_title": "Foundry Capacity Map",
                        "tool_metrics": [
                            {"label": "Node Tightness", "value": "Elevated"},
                            {"label": "Capex Intensity", "value": "High"},
                            {"label": "Margin Drift", "value": "Stable"},
                            {"label": "FX Sensitivity", "value": "Moderate"},
                        ],
                        "tool_rows": [
                            {"tenor": "Bull", "value_date": "Target", "swap_points": "191", "outright": "Packaging clears"},
                            {"tenor": "Base", "value_date": "Target", "swap_points": "182", "outright": "Healthy utilization"},
                            {"tenor": "Bear", "value_date": "Target", "swap_points": "161", "outright": "Capex digestion"},
                        ],
                        "tape_title": "TSM Trade Log",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Last"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:43:59.904", "bid": "176.02", "ask": "176.19", "mid": "176.15", "venue": "NYSE"},
                            {"time": "08:43:35.112", "bid": "175.95", "ask": "176.14", "mid": "176.04", "venue": "ARCA"},
                            {"time": "08:43:12.744", "bid": "175.88", "ask": "176.08", "mid": "175.99", "venue": "BATS"},
                        ],
                    },
                ],
            },
            {
                "id": "crypto",
                "label": "Crypto",
                "subtitle": "Exchange monitor, funding, and derivatives tape",
                "market_label": "Overnight",
                "workspace_tag": "24/7",
                "symbol_prompt": "Search token, venue, perp, or funding board...",
                "monitor_title": "Crypto Exchange Monitor",
                "monitor_columns": [
                    {"id": "symbol", "label": "Pair"},
                    {"id": "bias", "label": "Bias"},
                    {"id": "last", "label": "Last"},
                    {"id": "change", "label": "%"},
                    {"id": "focus", "label": "Focus"},
                ],
                "monitor_rows": [
                    {"symbol": "BTC/USD", "bias": "▲", "last": "71,842", "change": "+2.94", "focus": "Spot demand"},
                    {"symbol": "ETH/USD", "bias": "▲", "last": "4,024", "change": "+1.47", "focus": "ETF flows"},
                    {"symbol": "SOL/USD", "bias": "▲", "last": "186.4", "change": "+3.22", "focus": "Momentum"},
                    {"symbol": "BTC PERP", "bias": "▲", "last": "71,910", "change": "+3.08", "focus": "Funding"},
                ],
                "feed": [
                    {"time": "08:41:04", "source": "Flow", "headline": "BTC spot demand recovers while perp funding remains orderly."},
                    {"time": "08:35:19", "source": "Derivs", "headline": "Open interest rises without liquidation stress across major venues."},
                    {"time": "08:27:41", "source": "Pulse", "headline": "Exchange health indicators improve after a subdued Asia open."},
                    {"time": "08:20:13", "source": "Macro", "headline": "Dollar softness and risk appetite both support the crypto beta complex."},
                ],
                "symbols": [
                    {
                        "id": "btc-usd",
                        "ticker": "BTC/USD",
                        "name": "Bitcoin Spot",
                        "display_price": "$71,842",
                        "change_pct": 2.94,
                        "bid": "$71,834",
                        "ask": "$71,850",
                        "note": "Spot demand has returned without a disorderly funding spike.",
                        "story_title": "Bitcoin pushes higher as spot demand and derivative positioning stay balanced.",
                        "story_summary": "Exchange health, funding, and tape quality all suggest a constructive move rather than a crowded, fragile squeeze.",
                        "story_points": [
                            "Funding remains positive but controlled.",
                            "Open interest is rising alongside spot participation rather than replacing it.",
                            "Cross-venue spread behavior still looks orderly into the U.S. handoff.",
                        ],
                        "tool_title": "Funding & Basis Board",
                        "tool_metrics": [
                            {"label": "8h Funding", "value": "0.010%"},
                            {"label": "Basis", "value": "6.8% ann."},
                            {"label": "Open Interest", "value": "Rising"},
                            {"label": "Liquidations", "value": "Contained"},
                        ],
                        "tool_rows": [
                            {"tenor": "Binance", "value_date": "Funding", "swap_points": "0.010%", "outright": "Balanced"},
                            {"tenor": "Bybit", "value_date": "Funding", "swap_points": "0.012%", "outright": "Long bias"},
                            {"tenor": "CME", "value_date": "Basis", "swap_points": "6.8%", "outright": "Institutional premium"},
                        ],
                        "tape_title": "BTC/USD Perp Prints",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Last"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:48.211", "bid": "71,834", "ask": "71,850", "mid": "71,842", "venue": "Binance"},
                            {"time": "08:44:31.774", "bid": "71,820", "ask": "71,837", "mid": "71,829", "venue": "Bybit"},
                            {"time": "08:44:16.408", "bid": "71,806", "ask": "71,826", "mid": "71,816", "venue": "CME"},
                        ],
                    },
                    {
                        "id": "eth-usd",
                        "ticker": "ETH/USD",
                        "name": "Ethereum Spot",
                        "display_price": "$4,024",
                        "change_pct": 1.47,
                        "bid": "$4,022",
                        "ask": "$4,026",
                        "note": "Flows are constructive, but ETH still trades as a second-derivative beta to BTC risk.",
                        "story_title": "Ethereum grinds higher as ETF optimism and ecosystem flows keep improving.",
                        "story_summary": "Relative performance has stabilized, and cross-exchange pricing shows less stress than the previous two sessions.",
                        "story_points": [
                            "ETH/BTC relative weakness has paused for now.",
                            "Funding is positive but not stretched.",
                            "Options skew is improving alongside spot behavior.",
                        ],
                        "tool_title": "ETH Relative Strength Deck",
                        "tool_metrics": [
                            {"label": "ETH/BTC", "value": "Stable"},
                            {"label": "8h Funding", "value": "0.008%"},
                            {"label": "Skew", "value": "Improving"},
                            {"label": "L2 Activity", "value": "Firm"},
                        ],
                        "tool_rows": [
                            {"tenor": "Spot", "value_date": "Trend", "swap_points": "Firm", "outright": "ETF tailwind"},
                            {"tenor": "Perp", "value_date": "Funding", "swap_points": "0.008%", "outright": "Orderly"},
                            {"tenor": "Options", "value_date": "Skew", "swap_points": "-1.2", "outright": "Less defensive"},
                        ],
                        "tape_title": "ETH/USD Prints",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Last"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:40.024", "bid": "4,022", "ask": "4,026", "mid": "4,024", "venue": "Coinbase"},
                            {"time": "08:44:18.611", "bid": "4,020", "ask": "4,024", "mid": "4,022", "venue": "Kraken"},
                            {"time": "08:43:58.302", "bid": "4,017", "ask": "4,021", "mid": "4,019", "venue": "Binance"},
                        ],
                    },
                ],
            },
            {
                "id": "commodities",
                "label": "Commodities",
                "subtitle": "Curve, inventory context, and front-month prints",
                "market_label": "Global",
                "workspace_tag": "Curve",
                "symbol_prompt": "Search commodity, curve, inventory pulse, or refinery board...",
                "monitor_title": "Commodities Curve Monitor",
                "monitor_columns": [
                    {"id": "symbol", "label": "Contract"},
                    {"id": "bias", "label": "Bias"},
                    {"id": "last", "label": "Last"},
                    {"id": "change", "label": "%"},
                    {"id": "focus", "label": "Focus"},
                ],
                "monitor_rows": [
                    {"symbol": "CL", "bias": "▲", "last": "82.61", "change": "+0.37", "focus": "Supply premium"},
                    {"symbol": "GC", "bias": "▲", "last": "2,438", "change": "+0.22", "focus": "Real yields"},
                    {"symbol": "HG", "bias": "▼", "last": "4.71", "change": "-0.44", "focus": "China demand"},
                    {"symbol": "NG", "bias": "▲", "last": "2.91", "change": "+0.18", "focus": "Storage"},
                ],
                "feed": [
                    {"time": "08:40:27", "source": "Energy", "headline": "WTI holds a modest supply premium as inventories remain tight but orderly."},
                    {"time": "08:32:49", "source": "Metals", "headline": "Copper cools as traders reassess China-linked demand optimism."},
                    {"time": "08:24:22", "source": "Macro", "headline": "Gold remains bid on steady real-yield sensitivity and resilient reserve demand."},
                    {"time": "08:18:33", "source": "Pulse", "headline": "Commodity curves remain constructive without signaling panic in nearby contracts."},
                ],
                "symbols": [
                    {
                        "id": "cl",
                        "ticker": "CL",
                        "name": "WTI Crude",
                        "display_price": "$82.61",
                        "change_pct": 0.37,
                        "bid": "$82.58",
                        "ask": "$82.63",
                        "note": "Supply risk premium persists, but the curve still looks orderly rather than stressed.",
                        "story_title": "WTI holds firm as supply premium remains present without a disorderly curve shock.",
                        "story_summary": "Inventory and geopolitical headlines still support crude, though the term structure does not yet imply a chaotic shortage signal.",
                        "story_points": [
                            "Nearby curve stays constructive rather than explosive.",
                            "Refinery demand pulse improved modestly through the week.",
                            "Macro sensitivity still points to growth headlines as the next directional input.",
                        ],
                        "tool_title": "Curve & Inventory Board",
                        "tool_metrics": [
                            {"label": "Front Month", "value": "$82.61"},
                            {"label": "1-3M Spread", "value": "+0.86"},
                            {"label": "Inventory Pulse", "value": "Tight"},
                            {"label": "Freight", "value": "Stable"},
                        ],
                        "tool_rows": [
                            {"tenor": "1M", "value_date": "Curve", "swap_points": "+0.86", "outright": "Backwardated"},
                            {"tenor": "3M", "value_date": "Curve", "swap_points": "+1.74", "outright": "Supportive"},
                            {"tenor": "Stocks", "value_date": "Inventory", "swap_points": "-1.9%", "outright": "Draw"},
                        ],
                        "tape_title": "WTI Front-Month Prints",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Last"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:33.410", "bid": "82.58", "ask": "82.63", "mid": "82.61", "venue": "NYMEX"},
                            {"time": "08:44:17.094", "bid": "82.55", "ask": "82.60", "mid": "82.57", "venue": "ICE"},
                            {"time": "08:43:56.602", "bid": "82.50", "ask": "82.55", "mid": "82.52", "venue": "NYMEX"},
                        ],
                    },
                    {
                        "id": "gc",
                        "ticker": "GC",
                        "name": "Gold",
                        "display_price": "$2,438",
                        "change_pct": 0.22,
                        "bid": "$2,437",
                        "ask": "$2,439",
                        "note": "Real-yield sensitivity remains supportive as reserve and defensive demand stay firm.",
                        "story_title": "Gold steadies near highs as real-yield dynamics and reserve demand continue to support the metal.",
                        "story_summary": "Price action is orderly, and the combination of central-bank demand plus macro hedging continues to hold the tape together.",
                        "story_points": [
                            "Real-rate drift remains the main short-term driver.",
                            "Reserve accumulation keeps the structural bid in place.",
                            "Momentum is positive but less extended than the last breakout phase.",
                        ],
                        "tool_title": "Gold Macro Board",
                        "tool_metrics": [
                            {"label": "Real Yield Beta", "value": "High"},
                            {"label": "Reserve Demand", "value": "Firm"},
                            {"label": "Positioning", "value": "Constructive"},
                            {"label": "Volatility", "value": "Contained"},
                        ],
                        "tool_rows": [
                            {"tenor": "Spot", "value_date": "Trend", "swap_points": "Up", "outright": "Defensive bid"},
                            {"tenor": "1M", "value_date": "Range", "swap_points": "2410-2468", "outright": "Orderly"},
                            {"tenor": "Macro", "value_date": "Driver", "swap_points": "Real rates", "outright": "Key"},
                        ],
                        "tape_title": "Gold Futures Prints",
                        "tape_columns": [
                            {"id": "time", "label": "Timestamp"},
                            {"id": "bid", "label": "Bid"},
                            {"id": "ask", "label": "Ask"},
                            {"id": "mid", "label": "Last"},
                            {"id": "venue", "label": "Venue"},
                        ],
                        "tape_rows": [
                            {"time": "08:44:09.782", "bid": "2437", "ask": "2439", "mid": "2438", "venue": "COMEX"},
                            {"time": "08:43:49.036", "bid": "2436", "ask": "2438", "mid": "2437", "venue": "COMEX"},
                            {"time": "08:43:22.118", "bid": "2435", "ask": "2437", "mid": "2436", "venue": "OTC"},
                        ],
                    },
                ],
            },
        ],
    },
    "settings": {
        "themes": ["Mercury Ledger", "Signal Paper", "After Hours"],
        "active_theme": "Mercury Ledger",
        "billing_plan": "attas Plaza Pro Annual",
        "profile_name": "Alvin / Personal research desk",
        "storage_options": ["Filesystem", "SQLite", "Supabase", "S3", "attas hosted"],
        "active_storage": "Filesystem + SQLite edge cache",
    },
}


def get_dashboard_snapshot() -> Dict[str, Any]:
    return deepcopy(_DASHBOARD_SNAPSHOT)


def get_workspace(workspace_id: str) -> Optional[Dict[str, Any]]:
    for workspace in _DASHBOARD_SNAPSHOT["workspaces"]:
        if workspace["id"] == workspace_id:
            return deepcopy(workspace)
    return None
