"""
Phema storage schema declarations for `phemacast.core.phema_schema`.

Phemacast owns the persistence shape for stored Phemas and cached Phema snapshots.
These schemas should not live in Prompits because they describe a higher-level
content artifact rather than generic framework infrastructure.
"""

from __future__ import annotations

from typing import Any, Dict

from prompits.core.schema import TableSchema


def phemas_schema_dict() -> Dict[str, Any]:
    """Return the persisted Phema schema."""
    return {
        "name": "phemas",
        "description": "Persisted Phema blueprints managed through the Phemar UI.",
        "primary_key": ["id"],
        "rowSchema": {
            "id": {"type": "string"},
            "name": {"type": "string"},
            "description": {"type": "string"},
            "owner": {"type": "string"},
            "address": {"type": "string"},
            "tags": {"type": "json"},
            "input_schema": {"type": "json"},
            "output_schema": {"type": "json"},
            "sections": {"type": "json"},
            "meta": {"type": "json"},
            "created_at": {"type": "datetime"},
            "updated_at": {"type": "datetime"},
        },
    }


def phema_snapshots_schema_dict() -> Dict[str, Any]:
    """Return the persisted Phema snapshot schema."""
    return {
        "name": "phema_snapshots",
        "description": "Persisted static Phema snapshots generated by a Phemar.",
        "primary_key": ["id"],
        "rowSchema": {
            "id": {"type": "string"},
            "phema_id": {"type": "string"},
            "phema_name": {"type": "string"},
            "params_hash": {"type": "string"},
            "params": {"type": "json"},
            "tags": {"type": "json"},
            "snapshot": {"type": "json"},
            "cache_ttl_seconds": {"type": "integer"},
            "expires_at": {"type": "datetime"},
            "meta": {"type": "json"},
            "created_at": {"type": "datetime"},
            "updated_at": {"type": "datetime"},
        },
    }


def phemas_table_schema() -> TableSchema:
    """Return the Phema table schema."""
    return TableSchema(phemas_schema_dict())


def phema_snapshots_table_schema() -> TableSchema:
    """Return the Phema snapshot table schema."""
    return TableSchema(phema_snapshots_schema_dict())


__all__ = [
    "phemas_schema_dict",
    "phemas_table_schema",
    "phema_snapshots_schema_dict",
    "phema_snapshots_table_schema",
]
